// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// // @codescene(disable:"Complex Method")
class DefaultFirebaseOptions {
  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6uft_xIKD2wpQ_maVmsGLo41vJ81abpE',
    appId: '1:249456853413:android:01c8da2c2fc509ed42a84c',
    messagingSenderId: '249456853413',
    projectId: 'brainlytic-bc38f',
    storageBucket: 'brainlytic-bc38f.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa3YQiO72fKTC9ctYLfliyoGVRYh7tRag',
    appId: '1:249456853413:web:b0d0691dc205396c42a84c',
    messagingSenderId: '249456853413',
    projectId: 'brainlytic-bc38f',
    authDomain: 'brainlytic-bc38f.firebaseapp.com',
    storageBucket: 'brainlytic-bc38f.firebasestorage.app',
    measurementId: 'G-6RL8X3X5P4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVwAH84W3h0gESF5_PHWI0xJc-ho0DE5k',
    appId: '1:249456853413:ios:96c195e4dcaee2d342a84c',
    messagingSenderId: '249456853413',
    projectId: 'brainlytic-bc38f',
    storageBucket: 'brainlytic-bc38f.firebasestorage.app',
    androidClientId: '249456853413-0hltm44pea805kolbfi1q24lj40kgtko.apps.googleusercontent.com',
    iosClientId: '249456853413-9qrfjc3d9pj0qbuil8jiaalqfpfa9etf.apps.googleusercontent.com',
    iosBundleId: 'com.example.brainlytic',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVwAH84W3h0gESF5_PHWI0xJc-ho0DE5k',
    appId: '1:249456853413:ios:96c195e4dcaee2d342a84c',
    messagingSenderId: '249456853413',
    projectId: 'brainlytic-bc38f',
    storageBucket: 'brainlytic-bc38f.firebasestorage.app',
    androidClientId: '249456853413-0hltm44pea805kolbfi1q24lj40kgtko.apps.googleusercontent.com',
    iosClientId: '249456853413-9qrfjc3d9pj0qbuil8jiaalqfpfa9etf.apps.googleusercontent.com',
    iosBundleId: 'com.example.brainlytic',
  );

}